### ISSUE TITLE
error at setup execution

### ISSUE THREAD

**Issue by OSdave** [EcomDev/EcomDev_UrlRewrite#16]
hi Ivan,
I installed the extension on a 1.7.0.2, everything went fine locally, but when I deployed in preprod server I ran into an issue:

```
a:5:{i:0;s:328:"Error in file: "/data/www/sisley/sisleyinter/ecom/app/code/community/EcomDev/UrlRewrite/sql/ecomdev_urlrewrite_setup/mysql4-install-0.2.0.php" - SQLSTATE[HY000]: General error: 1419 You do not have the SUPER privilege and binary logging is enabled (you *might* want to use the less safe log_bin_trust_function_creators variable)";i:1;s:1020:"#0 /data/www/sisley/sisleyinter/ecom/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /data/www/sisley/sisleyinter/ecom/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '0.2.1')
#2 /data/www/sisley/sisleyinter/ecom/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('0.2.1')
#3 /data/www/sisley/sisleyinter/ecom/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /data/www/sisley/sisleyinter/ecom/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#t* want to use the less safe log_bin_trust_function_creators variable /data/www/sisley/sisleyinter/ecom/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /data/www/sisley/sisleyinter/ecom/app/Mage.php(683): Mage_Core_Model_App->run(Array)
#7 /data/www/sisley/sisleyinter/ecom/index.php(88): Mage::run('', 'store')
#8 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}
```

If I comment Ecomdev/UrlRewrite/sql/ecomdev_urlrewrite_setup/mysql4-install-0.2.0.php's line 500 - 545 (aka the declaration of the ECOMDEV_CLEAN_URL_KEY function) I can avoid the error, but then the function is not created and I guess it's not good: any idea on how to solve it?

thanx,
david

**Comment by OSdave** [comment]
just to let you know, the sysadmin enabled the binary logs and the setup script ran smoothly
